# Generated by Django 4.1 on 2022-09-05 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=80)),
                ("year", models.IntegerField()),
                ("cover_image", models.ImageField(upload_to="")),
                ("rating", models.IntegerField()),
                ("cast", models.ManyToManyField(blank=True, to="people.person")),
                (
                    "category",
                    models.ManyToManyField(blank=True, to="categories.category"),
                ),
                (
                    "director",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fk_persion",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
